services:
  api:
    build: .
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    command: >
      sh -c "mkdir -p /app/data &&
             [ ! -f /app/data/mood.csv ] && echo 'дата,настроение' > /app/data/mood.csv;
             uvicorn main:app --host 0.0.0.0 --port 10000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:10000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - UPLOAD_URL=http://api:10000/upload
    depends_on:
      - api