services:
  - type: web
    name: mood-app
    runtime: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    envVars:
      - key: PORT
        value: "10000"
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: "https://mood-app.onrender.com"
    healthCheckPath: /
